#  drone
build:
  image: golang:1.6
  environment:
    - GOPATH=/home/ubuntu
  commands:
    - BUILDTIME=`date -u '+%Y-%m-%d_%I:%M:%S%p'`
    - GITHASH=`git rev-parse HEAD`
    - go get -ldflags "-X main.Buildtime=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.Githash=`git rev-parse HEAD`" github.com/zgiles/ctuniverse/...
    - cd /home/ubuntu/bin
    - sha256sum ctuniverse > shasums
    - cd /home/ubuntu
    - tar -czvf ctuniverse-linux.tar.gz bin/
    - mv ctuniverse-linux.tar.gz /home/ubuntu/src/github.com/zgiles/ctuniverse/
